name: Convert DOCX to PDF

on:
  push:
    paths:
      - '**/*.docx'  # Trigger only when .docx files are pushed

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc
      run: sudo apt-get install -y pandoc texlive

    - name: Find and convert DOCX to PDF
      run: |
        find . -name '*.docx' -print0 | while IFS= read -r -d '' file; do
          output="${file%.docx}.pdf"
          pandoc "$file" -f docx -t pdf -o "$output"
        done

    - name: Upload PDFs
      uses: actions/upload-artifact@v3
      with:
        name: pdf-files
        path: '**/*.pdf'